version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:767397978963:task-definition/task-anyhealth-demo:1" 
        LoadBalancerInfo:
          ContainerName: "cntr-img-anyhealth"
          ContainerPort: 8080